### ISSUE TITLE
Suggestion to improve experience for admins of larger installs

### ISSUE THREAD

**Issue by techknowlogick** [pat-s/alfred-gitea#1]
As an admin of Gitea.com when the repos sync they all show up when searching, instead of using the repo search endpoint perhaps you could do something like Drone (https://github.com/drone/go-scm/blob/master/scm/driver/gitea/repo.go#L42) where it fetches only the repos that you are a collaborator of.

I believe updating the URL at https://github.com/pat-s/alfred-gitea/blob/main/source/gitea.py#L45 would likely be the only change required, I can't test as I am unable to clear the cache.

Edit: I should read the README as I discovered how to clear cache, and will now test the suggested change, if works I will send PR.

Edit x2: Just updating the URL doesn't work. Likely need to look into changing some logic in update.py as well.

**Comment by pat-s** [comment]
Thanks. Sounds legit!

Calling `tea reset` and updating the url should do the trick. I will have a look.

**Comment by pat-s** [comment]
Please try https://github.com/pat-s/alfred-gitea/releases/tag/v1.1.0.
Now using the suggested endpoint and fixed an issue in `tea reset`.

**Comment by techknowlogick** [comment]
Awesome. Thanks!
Closing this now.
