### ISSUE TITLE
Can't open in browser

### ISSUE THREAD

**Issue by bowencool** [pat-s/alfred-gitea#4]
<img width="827" alt="image" src="https://user-images.githubusercontent.com/20217146/161215121-a79d4a85-9f39-4883-8d96-f0db2be9571d.png">

**Comment by bowencool** [comment]
Nothing happened, no errors

**Comment by bowencool** [comment]
`quick_open` is set `true`

**Comment by bowencool** [comment]
It works when `quick_open` is set `false`

**Comment by pat-s** [comment]
Thanks. Should be fixed in v2.0.1
